[package]
name = "conreg-cms"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.46"
anyhow = "1"
reqwest = { version = "0.12.22", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tokio = "1.47.1"
