name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install musl tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Add musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Check
        run: cargo check --bin conreg-server --target x86_64-unknown-linux-musl
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: conreg-server
#          path: target/x86_64-unknown-linux-musl/release/conreg-server
#          retention-days: 5
#          overwrite: 'true'